In [3]:
import gym
import PIL
from IPython import display
import numpy as np
from IPython.display import clear_output
import time
import sys

In [4]:
env = gym.make('FrozenLake-v0')
for i_episode in range(1):
    observation = env.reset()
    for t in range(100):
        env.render()
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        print(observation)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()


SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Up)
SFFF
FHFH
FFFH
HFFG
1
  (Down)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Up)
SFFF
FHFH
FFFH
HFFG
1
  (Up)
SFFF
FHFH
FFFH
HFFG
0
  (Up)
SFFF
FHFH
FFFH
HFFG
1
  (Up)
SFFF
FHFH
FFFH
HFFG
2
  (Down)
SFFF
FHFH
FFFH
HFFG
1
  (Up)
SFFF
FHFH
FFFH
HFFG
5
Episode finished after 11 timesteps


In [6]:
action_n=env.action_space.n
observation_n=env.observation_space.n

In [7]:
qtable = np.zeros((observation_n, action_n))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
total_episodes = 15000
learning_rate = 0.8
max_steps_in_episode = 99
gamma = 0.9
# Exploration parameters
epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.1 
decay_rate = 0.005   

In [9]:
rewards=[]
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    print('episode {}'.format(episode))
    for step in range(max_steps_in_episode):
        random_no = np.random.uniform(0, 1)
        
        ## exploitation (taking the biggest Q value for this state)
        env.render()
        if random_no > epsilon:
            action = np.argmax(qtable[state,:])

        # exploration
        else:
            action = env.action_space.sample()
        # continue with the new state
        observation, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[observation, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = observation
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
    if episode%5==0:
        clear_output()  
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: {}".format(sum(rewards)/total_episodes))
print(qtable)

episode 14996

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
episode 14997

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
episode 14998

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
episode 14999

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
 

In [26]:
env.reset()
ep0,ep1,ep2=[],[],[]
action0,action1,action2 = [],[],[]
for episode in range(3):
    state = env.reset()
    if(episode==0):
        ep0.append(state)
    elif(episode==1):
        ep1.append(state)
    elif(episode==2):
        ep1.append(state)
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode+1)

    for step in range(max_steps_in_episode):
#         env.render()
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        if(episode==0):
            ep0.append(new_state)
            action0.append(action)
        elif(episode==1):
            ep1.append(new_state)
            action1.append(action)
        elif(episode==2):
            ep2.append(new_state)
            action2.append(action)
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            if(episode==0):
                action0.append(action)
            elif(episode==1):
                action1.append(action)
            elif(episode==2):
                action2.append(action)
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  1
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 25
****************************************************
EPISODE  2
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 50
****************************************************
EPISODE  3
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 20


In [17]:
fr=['S','F','F','F','F','H','F','H','F','F','F','H','H','F','F','G']

In [19]:
dict={}
dict[0]='Left'
dict[1]='Down'
dict[2]='Right'
dict[3]='Up'

In [28]:
counter=1
while True:
    for ind,col in enumerate(ep1):
        print('***********')
        print('Episode 2')
        print('  ')
#         print('({})'.format(dict[action2[ind]]))
        for i,ele in enumerate(fr):
            if(i==col):
                if(counter%4==0):
                    print('\x1b[6;30;43m'+ele+'\x1b[0m')
                else:
                    print('\x1b[6;30;43m'+ele+'\x1b[0m', end =' ')
                counter+=1
            else:
                if(counter%4==0):
                    print(ele)
                else:
                    print(ele, end =' ')
                counter+=1
        time.sleep(0.4)
        display.clear_output(wait=True)

***********
Episode 2
  
S F F F
F H F H
F F F H
H F F G


KeyboardInterrupt: 

In [25]:
len(action1)

60